# Generated by Django 4.2.1 on 2023-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/images/goku.jpg', upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='societymember',
            name='pic',
            field=models.FileField(default='media/images/goku.jpg', upload_to='media/images'),
        ),
    ]
