# Generated by Django 4.2.1 on 2023-06-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0005_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='heading',
            new_name='media_type',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='main_body',
        ),
        migrations.AddField(
            model_name='notice',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
