# Generated by Django 4.2.1 on 2023-06-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0006_rename_heading_notice_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
