# Generated by Django 4.2.1 on 2023-06-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0009_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='header',
        ),
    ]
