# Generated by Django 4.2.2 on 2023-06-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocietyMember',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Chairman',
            new_name='Teacher',
        ),
    ]
