# Generated by Django 4.2.2 on 2023-07-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0002_student_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
