# Generated by Django 4.2.2 on 2023-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0002_rename_societymember_student_rename_chairman_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventGallery',
            new_name='Events',
        ),
        migrations.RemoveField(
            model_name='student',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='job_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='student',
            name='no_of_familymembers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vehicle_details',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='house_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.FileField(default='media/images/user.png', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.FileField(default='media/images/user.png', upload_to='media/images'),
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
