# Generated by Django 4.2.2 on 2023-06-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0003_rename_eventgallery_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='videofile',
            field=models.FileField(null=True, upload_to='media/videos/', verbose_name=''),
        ),
    ]
