# Generated by Django 4.2.2 on 2023-06-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0004_alter_events_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('club_activity', models.TextField()),
                ('club_pic', models.FileField(default='media/clubs/def.jpg', upload_to='media/clubs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.user')),
            ],
        ),
    ]
