# Generated by Django 4.2.2 on 2023-06-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0006_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='my address'),
        ),
    ]
