# Generated by Django 4.2.2 on 2023-06-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0007_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='events',
            name='videofile',
        ),
        migrations.AddField(
            model_name='events',
            name='event_name',
            field=models.CharField(default='This is event', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='pic',
            field=models.FileField(default='media/images/ds.png', upload_to='media/images'),
        ),
    ]
