# Generated by Django 4.2.2 on 2023-06-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0008_remove_events_media_type_remove_events_videofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='club_pic',
            field=models.FileField(default='media/images/ds.png', upload_to='media/images'),
        ),
    ]
