# Generated by Django 4.2.2 on 2023-07-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0012_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
