# Generated by Django 4.2.2 on 2023-07-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0014_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
